# Generated by Django 4.1.1 on 2022-11-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
